<a href="https://colab.research.google.com/github/BoburH/Data_science/blob/main/2_1_3_Sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tartiblash sort

In [ ]:
import numpy as np

In [ ]:
# Sorting
# data
arr = np.random.rand(4)    # 4 elementli taxminiy bir o'lchamli massiv
arr

array([0.56575962, 0.11443995, 0.29677629, 0.23206144])

In [ ]:
# sort funksiyasi
# 1 usul
sorted_arr = np.sort(arr)      # arr massivnining tartiblangan yangi ko'rinishi
sorted_arr

array([0.11443995, 0.23206144, 0.29677629, 0.56575962])

In [ ]:
# 2 usul
arr.sort()       # arr ning tartiblangan ko'rinishi
arr

array([0.11443995, 0.23206144, 0.29677629, 0.56575962])

In [ ]:
# teskari tartiblash
rev_arr = -np.sort(-arr)      # arr ning teskari tartiblashgan ko'rinishi
rev_arr

array([0.56575962, 0.29677629, 0.23206144, 0.11443995])

In [ ]:
# 2 D array (massiv)
arr2d = np.random.randn(2,4)     # (2,4) o'lchamli massiv
arr2d

array([[ 0.63952347, -1.06663673, -1.57526584,  1.31293521],
       [-0.02719015,  0.81166768, -0.18168961,  1.4689049 ]])

In [ ]:
# axis = 1 qator
row_srt =np.sort(arr2d, axis=1)  # elementlarni qatorlar bo'yicha tartiblaydi
row_srt

array([[-1.57526584, -1.06663673,  0.63952347,  1.31293521],
       [-0.18168961, -0.02719015,  0.81166768,  1.4689049 ]])

In [ ]:
# axis = 0 ustun
col_str = np.sort(arr2d, axis=0)     # ustun bo'yicha tartiblaydi
col_str

array([[-0.02719015, -1.06663673, -1.57526584,  1.31293521],
       [ 0.63952347,  0.81166768, -0.18168961,  1.4689049 ]])