<a href="https://colab.research.google.com/github/BoburH/Data_science/blob/main/2_1_3__Logical_setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mantiqiy shart operatorlarini massiv operatorlari sifatida qo'llash

In [1]:
import numpy as np

# *where* operatori yordamida amalga oshiriladi

In [5]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [6]:
# Shart
cond = np.array([True, False, True, True, False])

In [7]:
# where
result = np.where(cond, xarr, yarr)     # cond True bo'lganda xarr elementini oladi, aks holda yarr elementi olinadi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [10]:
arr = np.random.randn(4,4)
arr

array([[-0.72243984,  0.28754614, -0.40713625,  0.93150985],
       [ 0.36679249, -0.2335454 , -0.85131173, -0.79130154],
       [-0.37562969,  0.35225047, -0.37522562, -0.37857321],
       [ 1.03057744, -1.62500058,  1.43849029,  0.30144585]])

In [12]:
result = np.where(arr<0, -2, 2)
result

array([[-2,  2, -2,  2],
       [ 2, -2, -2, -2],
       [-2,  2, -2, -2],
       [ 2, -2,  2,  2]])