<a href="https://colab.research.google.com/github/BoburH/Data_science/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Boolean indekslash

In [1]:
import numpy as np

In [2]:
# Ismlar

In [3]:
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javhoir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javhoir', 'Elyor'],
      dtype='<U8')

In [4]:
# data
data = np.random.rand(7,4)
data

array([[0.38612799, 0.84889422, 0.81369572, 0.55660211],
       [0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.45291594, 0.37626239, 0.12427894, 0.74583466],
       [0.04148198, 0.20553509, 0.74844752, 0.05519567],
       [0.63498842, 0.61404423, 0.86021701, 0.7655817 ],
       [0.21548846, 0.14514722, 0.17478762, 0.20861807],
       [0.00649586, 0.53967451, 0.71032017, 0.26222937]])

In [6]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [8]:
data[names == 'Hasan']   # Hasanga tegishli ma'lumotlar ajratib olish. Bu yerda Hasanning names massividagi indeksiga mutanosib ravishda dataning o'sha indeks ma'lumotlari qaytariladi

array([[0.38612799, 0.84889422, 0.81369572, 0.55660211],
       [0.63498842, 0.61404423, 0.86021701, 0.7655817 ]])

In [9]:
data[names == 'Elyor']

array([[0.04148198, 0.20553509, 0.74844752, 0.05519567],
       [0.00649586, 0.53967451, 0.71032017, 0.26222937]])

In [10]:
data[names == 'Hasan', 2:]      # Hasanning ma'lumotlaridagi ikkinchidan keyingi ustun ma'lumotlarini olish

array([[0.81369572, 0.55660211],
       [0.86021701, 0.7655817 ]])

In [11]:
data[names != 'Hasan']      # Hasanga teng bo'lmagan ismlarga tegishli ma'lumotlarni qaytarish

array([[0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.45291594, 0.37626239, 0.12427894, 0.74583466],
       [0.04148198, 0.20553509, 0.74844752, 0.05519567],
       [0.21548846, 0.14514722, 0.17478762, 0.20861807],
       [0.00649586, 0.53967451, 0.71032017, 0.26222937]])

In [12]:
data[~(names == 'Hasan')]     # Bu ham Hasanga teng bo'lmaganlarni qaytarish uchun

array([[0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.45291594, 0.37626239, 0.12427894, 0.74583466],
       [0.04148198, 0.20553509, 0.74844752, 0.05519567],
       [0.21548846, 0.14514722, 0.17478762, 0.20861807],
       [0.00649586, 0.53967451, 0.71032017, 0.26222937]])

In [13]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javhoir' 'Elyor']
[[0.38612799 0.84889422 0.81369572 0.55660211]
 [0.38579289 0.22490212 0.88937932 0.5481899 ]
 [0.45291594 0.37626239 0.12427894 0.74583466]
 [0.04148198 0.20553509 0.74844752 0.05519567]
 [0.63498842 0.61404423 0.86021701 0.7655817 ]
 [0.21548846 0.14514722 0.17478762 0.20861807]
 [0.00649586 0.53967451 0.71032017 0.26222937]]


In [18]:
mask = (names == 'Hasan') | (names == 'Husan')     # bu yerda | belgisi or ya'ni yoki sifatida ishlatilib ikki elementlar uchun ishlatiladi
mask

array([ True,  True, False, False,  True, False, False])

In [19]:
data[mask]

array([[0.38612799, 0.84889422, 0.81369572, 0.55660211],
       [0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.63498842, 0.61404423, 0.86021701, 0.7655817 ]])

In [20]:
data

array([[0.38612799, 0.84889422, 0.81369572, 0.55660211],
       [0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.45291594, 0.37626239, 0.12427894, 0.74583466],
       [0.04148198, 0.20553509, 0.74844752, 0.05519567],
       [0.63498842, 0.61404423, 0.86021701, 0.7655817 ],
       [0.21548846, 0.14514722, 0.17478762, 0.20861807],
       [0.00649586, 0.53967451, 0.71032017, 0.26222937]])

In [21]:
data[data<0.2]

array([0.12427894, 0.04148198, 0.05519567, 0.14514722, 0.17478762,
       0.00649586])

In [22]:
data[data<0.2] = 1

In [23]:
data

array([[0.38612799, 0.84889422, 0.81369572, 0.55660211],
       [0.38579289, 0.22490212, 0.88937932, 0.5481899 ],
       [0.45291594, 0.37626239, 1.        , 0.74583466],
       [1.        , 0.20553509, 0.74844752, 1.        ],
       [0.63498842, 0.61404423, 0.86021701, 0.7655817 ],
       [0.21548846, 1.        , 1.        , 0.20861807],
       [1.        , 0.53967451, 0.71032017, 0.26222937]])