<a href="https://colab.research.google.com/github/BoburH/Data_science/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
np.show_config

<function numpy.__config__.show()>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
array = np.array([2,4,6,9,12])
array

array([ 2,  4,  6,  9, 12])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [3]:
zeros = np.zeros((3,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
arr = np.random.randint(0,2000,1)
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
import numpy as np

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [6]:
arr = np.zeros(12)

arr[5]=1

print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [7]:
vektor = np.arange(20,60)

print(vektor)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [8]:
rev_vektor = vektor[::-1]

print(rev_vektor)

[59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36
 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [9]:
matrix = np.arange(12,21).reshape(3,3)

print(matrix)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [10]:
arr = np.array([3, 7, 0, 0, 9, 0])

arr_nonzero = np.where(arr != 0)
print(arr_nonzero)

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [11]:
matrix = np.random.rand(2,2,2)
matrix

array([[[0.24971779, 0.75291173],
        [0.25736432, 0.76003938]],

       [[0.15241746, 0.34253976],
        [0.01948842, 0.5283672 ]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [12]:
arr = np.random.rand(9,9)
min = np.min(arr)
max = np.max(arr)
print(f"Massivning eng katta elementi: {max}, \neng kichigi: {min}")

Massivning eng katta elementi: 0.9938366606923568, 
eng kichigi: 0.009522702755829004


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [13]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [14]:
matrix1 = np.random.rand(6,3)
matrix2 = np.random.rand(3,4)
a = np.dot(matrix1, matrix2)
print(a)

[[1.11836323 0.61228731 0.59638741 0.4345783 ]
 [0.6009222  0.45094679 0.45639529 0.38639618]
 [0.20223222 0.14031213 0.14643872 0.11935874]
 [1.42143313 0.93463724 0.80900373 0.66759615]
 [0.90328023 0.97386442 0.41162999 0.55582512]
 [0.95494765 0.90982825 0.33976021 0.46244794]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1,2])
b = np.array([4,5])
a > b
a >= b
a < b
a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-25-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-25-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [21]:
arr = np.random.randint(1,21,10)
arr1 = np.random.randint(1,18,10)
print(arr)
print(arr1)

inter = np.intersect1d(arr,arr1)
print(inter)


[17 17 10 14 18  4 13 19 18  1]
[12 13 13 10  4 15 14  6  6 11]
[ 4 10 13 14]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [30]:
arr = np.random.randn(10)
condition = np.where(arr>0)
pos_arr = arr[condition]
print(pos_arr)
int_arr = np.floor(pos_arr)
print(int_arr)

[0.16564547 1.18318315 0.19928778 0.8386339  1.23880586]
[0. 1. 0. 0. 1.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [37]:
arr = np.random.randint(0,3, size=(3,3))
arr

array([[1, 1, 2],
       [2, 2, 1],
       [2, 0, 0]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [41]:
ar = np.random.randint(1,30, 10)
ar
sort_ar = np.sort(ar)
print(sort_ar)

[11 15 15 16 18 18 19 23 23 24]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [43]:
A = np.random.randint(1, 10, 5)
B = np.random.randint(1, 10, 5)
np.array_equal(A,B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [45]:
arr1 = np.random.randint(20, size=(6,3))
arr2 = np.random.randint(10, size=(3,4))
mult = np.dot(arr1, arr2)
print(mult)

[[211 128 114 229]
 [127  50 108 181]
 [136  81 133 184]
 [ 71  57 101 104]
 [189 101 139 237]
 [112  40 106 169]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [52]:
t1 = np.random.randint(1, 20, 5)
print(t1)
max_t1 = np.argmax(t1)
t1[max_t1] = 0
print(t1)

[ 9 19 18  4  5]
[ 9  0 18  4  5]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [54]:
import numpy as np
from datetime import datetime, timedelta
today = datetime.now()
one_day = timedelta(days=1)
yesterday = today - one_day
tomorrow = today + one_day

today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)

print(today_np)
print(yesterday_np)
print(tomorrow_np)




2023-08-21T11:54:13.818661
2023-08-20T11:54:13.818661
2023-08-22T11:54:13.818661


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [55]:
import numpy as np

start_date = np.datetime64('2016-01-01')

end_date = np.datetime64('2016-01-31')

all_dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), np.timedelta64(1, 'D'))

print(all_dates)


['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [57]:
import numpy as np

# Generate a random array with negative and positive numbers
random_array = np.random.uniform(-10, 10, size=10)

# Method 1: Using modulo (%)
integer_part_modulo = random_array[random_array > 0] % 1

# Method 2: Using np.floor()
integer_part_floor = np.floor(random_array[random_array > 0])

# Method 3: Using astype()
integer_part_astype = (random_array[random_array > 0]).astype(int)

# Method 4: Using np.trunc()
integer_part_trunc = np.trunc(random_array[random_array > 0])

print("Original Array:", random_array)
print("Integer Parts (Modulo):", integer_part_modulo)
print("Integer Parts (Floor):", integer_part_floor)
print("Integer Parts (astype):", integer_part_astype)
print("Integer Parts (trunc):", integer_part_trunc)


Original Array: [-3.97021506  4.95421207  4.19645679 -8.11051372  5.24824016  5.60724061
 -1.40158376  6.36576038  5.62207539 -8.33409398]
Integer Parts (Modulo): [0.95421207 0.19645679 0.24824016 0.60724061 0.36576038 0.62207539]
Integer Parts (Floor): [4. 4. 5. 5. 6. 5.]
Integer Parts (astype): [4 4 5 5 6 5]
Integer Parts (trunc): [4. 4. 5. 5. 6. 5.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [58]:
import numpy as np

# Ixtiyoriy massivlar yaratish
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([0.5, 1.5, 2.5, 3.5, 4.5])
array3 = np.array([-2, -1, 0, 1, 2])

# np.add.reduce (yoki np.sum) funksiyasini ishlatib yeg'indini hisoblash
sum_array1 = np.add.reduce(array1)
sum_array2 = np.sum(array2)
sum_array3 = np.add.reduce(array3)

print("Array 1:", array1, "Sum:", sum_array1)
print("Array 2:", array2, "Sum:", sum_array2)
print("Array 3:", array3, "Sum:", sum_array3)


Array 1: [1 2 3 4 5] Sum: 15
Array 2: [0.5 1.5 2.5 3.5 4.5] Sum: 12.5
Array 3: [-2 -1  0  1  2] Sum: 0


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [59]:
import numpy as np

# Boshlang'ich vektor
original_vector = np.array([1, 2, 3, 4, 5])

# Ketma-ket 3 ta nol qo'shish
new_vector = np.zeros(len(original_vector) * 4 - 3)
new_vector[::4] = original_vector

print("Original Vector:", original_vector)
print("Modified Vector:", new_vector)


Original Vector: [1 2 3 4 5]
Modified Vector: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [60]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

# Berilgan a massivi
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# b massivini o'lchamlarini aniqlash
n = 4  # b massivining ustunlar soni (strok soni)
m = len(a) - n + 1  # b massivining qatorlar soni (ustun soni)

# as_strided funktsiyasi orqali b massivini yaratish
b = as_strided(a, shape=(m, n), strides=(a.itemsize, a.itemsize))

print(b)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [61]:
import numpy as np

# Ixtiyoriy sonlardan tashkil topgan massiv yaratish
random_array = np.random.randint(0, 10, size=20)

# O'xshash qiymatni topuvchi funksiya
def most_common_value(arr):
    unique_values, counts = np.unique(arr, return_counts=True)
    most_common_index = np.argmax(counts)
    return unique_values[most_common_index]

# O'xshash qiymatni topish
common_value = most_common_value(random_array)

print("Random Array:", random_array)
print("Most Common Value:", common_value)


Random Array: [6 9 4 5 4 3 4 5 0 2 9 2 8 6 2 8 6 0 9 1]
Most Common Value: 2


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`