<a href="https://colab.research.google.com/github/BoburH/Data_science/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# vector that has 4 elements

In [3]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

# A 2x4 elements matrix:

In [4]:
A = np.arange(8).reshape(2,4)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
A.shape

(2, 4)

In [6]:
A.size

8

# A 2x2x4 tensor:

In [7]:
T = np.arange(16).reshape(2,2,4)
T

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
T.shape

(2, 2, 4)

In [9]:
T.size

16

# 4D array (2,2,2,2):

In [10]:
T2 = np.random.randint(10, size=(2,2,2,2))
T2

array([[[[5, 7],
         [8, 8]],

        [[8, 8],
         [5, 1]]],


       [[[6, 1],
         [3, 3]],

        [[0, 0],
         [0, 3]]]])

In [11]:
T2.shape

(2, 2, 2, 2)

In [12]:
T2.size

16

# Vectorni scalar ga ko'pyatirish

In [13]:
v

array([1, 2, 3, 4])

In [14]:
v*2

array([2, 4, 6, 8])

In [15]:
v1 = v*2

In [16]:
v1

array([2, 4, 6, 8])

In [17]:
# dot funksiyasi orqali massivning har bir elementi boshqa massivning aynan o'sha o'rindagi elementiga ko'paytirilib summasini qaytaradi.
np.dot(v, v1)

60

In [18]:
print("v + v1 {}".format(v + v1))
print("v1 - v {}".format(v1-v))

v + v1 [ 3  6  9 12]
v1 - v [1 2 3 4]


In [19]:
# Square matrix
A1 = np.random.randint(5, size=(3,3))
A1

array([[1, 3, 0],
       [2, 1, 4],
       [2, 3, 1]])

In [20]:
  # Identity matrix
  I3 = np.identity(3, dtype=int)
  I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
I4 = np.identity(4, dtype=int)
I4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
I5 = np.identity(5, dtype = int)
I5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
B = np.random.randint(5, size = (3,4))
B

array([[0, 0, 4, 1],
       [2, 3, 4, 2],
       [1, 3, 3, 2]])

In [24]:
# First row
B[0]

array([0, 0, 4, 1])

In [25]:
# Second row
B[1]

array([2, 3, 4, 2])

In [26]:
# First column
B[:,0]

array([0, 2, 1])

In [27]:
# Second column
B[:, 1]

array([0, 3, 3])

In [28]:
# The element positioned in 3rd row in 4th column
B[2,3]


2

In [33]:
A2 = np.random.randint(5, size = (3,2))
A2

array([[0, 4],
       [2, 2],
       [2, 2]])

In [34]:
A3 = np.random.randint(5, size= (2,3))
A3

array([[3, 4, 0],
       [4, 0, 3]])

In [35]:
np.matmul(A2,A3)

array([[16,  0, 12],
       [14,  8,  6],
       [14,  8,  6]])

In [36]:
I1 = np.identity(3, dtype= int)
I1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
A3 = np.array([[10,14,8],
               [16,16,16],
               [14,18,12]])
A3


array([[10, 14,  8],
       [16, 16, 16],
       [14, 18, 12]])

In [39]:
np.matmul(I1, A3)

array([[10, 14,  8],
       [16, 16, 16],
       [14, 18, 12]])

In [40]:
np.matmul(A3, I1)

array([[10, 14,  8],
       [16, 16, 16],
       [14, 18, 12]])

In [42]:
A4 = np.random.randint(3, size= (3, 4))
A4

array([[2, 0, 0, 1],
       [2, 1, 2, 1],
       [0, 1, 0, 0]])

In [43]:
A4.T

array([[2, 2, 0],
       [0, 1, 1],
       [0, 2, 0],
       [1, 1, 0]])